name: rank-actions
on: [push]
jobs:
  rank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: rank
        run: node ./gen_list.js > rank.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add rank.md
          git commit -m 'Update rank.md'
          git push
